#!/bin/sh
dnf install  wget zip -y
rm -rf  v2.latest.zip
rm -rf  dplyd-orchst-2.latest
wget   "https://github.com/ARStorms/dplyd-orchst/archive/refs/tags/v2.latest.zip"
unzip   v2.latest.zip
cd      dplyd-orchst-2.latest
./dplyd-orchst-instl
cd      ..
rm -rf  v2.latest.zip
rm -rf  dplyd-orchst-2.latest
