#!/bin/sh
yield=$(python3 /sbin/dplyd-orchst-prjct-create.py "$1")
if [ "$?" != 0 ]
then
         echo $yield
         exit
fi
useradd  "$yield"
mkdir    "/home/$yield/.ssh"
cp       "/root/.ssh/authorized_keys" "/home/$yield/.ssh/"
chmod    -R 0700                      "/home/$yield/.ssh"
touch    "/home/$yield/.prmtr"; chmod 0600 "/home/$yield/.prmtr"
mkdir    "/home/$yield/.plate"; chmod 0700 "/home/$yield/.plate"
mkdir    "/home/$yield/.store"; chmod 0700 "/home/$yield/.store"
chown    -R $yield:$yield "/home/$yield"; restorecon -r "/home/$yield"
dplyd-orchst-prjct-prfl-prprgt  "$yield"
loginctl enable-linger          "$yield"
