#!/bin/sh
rm -rf 2.latest.zip
rm -rf dplyd-orchst-2.latest
wget  "https://github.com/ARStorms/dplyd-orchst/archive/refs/tags/2.latest.zip"
unzip  2.latest.zip
cd     dplyd-orchst-2.latest
./dplyd-orchst-instl
cd     ..
rm -rf 2.latest.zip
rm -rf dplyd-orchst-2.latest
