#!/bin/sh
mkdir -p $HOME/.local/bin
python3 /sbin/dplyd-orchst-prjct-launch.py
if [ "$?" != 0 ]
then
        dplyd-orchst-prjct-shtdwn
        exit 1
fi
chmod   0700 $HOME/.local/bin/*
"$HOME/.local/bin/dplyd-orchst-prjct-launchCode"
if [ "$?" != 0 ]
then
        dplyd-orchst-prjct-shtdwn
        exit 1
fi
