#!/bin/sh
if [ "$1" == "" ]
then
	echo "Project ID not provided"
	exit
fi
if ! id -u $1 > /dev/null
then
	echo "Project does not exist"
	exit
fi
if findmnt -T "/home/$1" | grep -q "/home/prjct-"
then
	echo "Project has a storage already"
	exit
fi
if [ "$2" == "" ]
then
	echo "Storage link not provided"
	exit
fi
if [ !  -e "$2" ]
then
	echo "Storage does not exist"
	exit
fi
if findmnt -n "$2"
then
	echo "Storage in use by a project"
	exit
fi
rm         -rf "/home/$1"
mkdir      "/home/$1"
dd         if=/dev/zero of="$2" bs=1G status=none > /dev/null 2> /dev/null
mkfs.ext4  -q "$2"
uuid=$(blkid | grep "$2" | sed -r 's/\/dev.+ UUID="|" .+$//gI')
fstabFile='/etc/fstab'
sed        -i "/\/home\/$1/d" $fstabFile
sed        -i '/^$/d' $fstabFile
sed        -i '${/[^$\]/s/$/\n/}' $fstabFile
echo       "UUID=$uuid /home/$1 ext4 defaults 0 2" | tee -a $fstabFile
sed        -i '/^$/d' $fstabFile
systemctl  daemon-reload
mount      -a
rsync      -avq "/etc/skel/."[0-9a-zA-Z]*     "/home/$1"
mkdir      "/home/$1/.ssh"
cp         "/root/.ssh/authorized_keys"       "/home/$1/.ssh/"
chmod      -R 0700                            "/home/$1/.ssh"
touch      "/home/$1/.prmtr"  ; chmod 0600    "/home/$1/.prmtr"
mkdir      "/home/$1/.plate"  ; chmod 0700    "/home/$1/.plate"
mkdir      "/home/$1/.store"  ; chmod 0700    "/home/$1/.store"
chown      -R $1:$1 "/home/$1"; restorecon -r "/home/$1"
