#!/bin/sh
if [ "$1" == "" ]
then
	echo "Swap storage link not provided"
	exit
fi
if [ !  -e "$1" ]
then
	echo "Swap storage does not exist"
	exit
fi
if findmnt -n "$1"
then
	echo "Swap storage in use by something else"
	exit
fi
dd         if=/dev/zero of="$1"       bs=1G > /dev/null 2> /dev/null
mkfs.ext4  -q "$1"
rm         -rf  /swap
mkdir      /swap
mount      "$1" /swap
touch      /swap/swap
dd         if=/dev/zero of=/swap/swap bs=1G > /dev/null 2> /dev/null
chown      -R root:root /swap
chmod      -R 700 /swap
chmod      -R 600 /swap/swap
mkswap     /swap/swap
swapon     /swap/swap
swapon     -a
uuid=$(blkid | grep "$1" | sed -r 's/\/dev.+ UUID="|" .+$//gI')
fstabFile='/etc/fstab'
sed        -i "/\/swap/d" $fstabFile
sed        -i '/^$/d'     $fstabFile
sed        -i '${/[^$\]/s/$/\n/}' $fstabFile
echo       "UUID=$uuid /swap ext4 defaults 0 0" | tee -a $fstabFile
echo       "/swap/swap  swap swap sw       0 0" | tee -a $fstabFile
sed        -i '/^$/d' $fstabFile
systemctl  daemon-reload
mount      -a
swapon     -a
