#!/bin/sh
if [ "$1" == "" ]
then
	echo "Project ID not provided"
	exit
fi
if ! id -u $1 > /dev/null
then
	echo "Project does not exist"
	exit
fi
python3 /sbin/dplyd-orchst-prjct-dnsid-cnfgr.py "$1" "$2" "$3"
if [ "$?" != 0 ]
then
        exit
fi
dplyd-orchst-prjct-prfl-prprgt "$1"
