#!/bin/sh
if [ "$1" == "" ]
then
	echo "Project ID not provided"
	exit
fi
if ! id -u $1 > /dev/null
then
	echo "Project does not exist"
	exit
fi
systemctl stop  nginx
python3   /sbin/dplyd-orchst-prjct-https-intlz.py "$1"
systemctl start nginx
