#!/bin/sh
podman stop --all --time 300
pulse=$(podman   ps    | grep software)
while [ "$pulse" != "" ]
do
        sleep 1
done
podman container rm -a
pulse=$(podman   ps -a | grep software)
while [ "$pulse" != "" ]
do
        sleep 1
done
podman image     rm -a
pulse=$(podman images  | grep software)
while [ "$pulse" != "" ]
do
        sleep 1
done
podman unshare chown -R 0:0 .prmtr
podman unshare chown -R 0:0 .plate
podman unshare chown -R 0:0 .store
crontab -r ; crontab -l
echo "Shutdown complete"
