#!/bin/sh
if [ "$1" == "" ]
then
	echo "Project ID not provided"
	exit
fi
if ! id -u $1 > /dev/null
then
	echo "Project does not exist"
	exit
fi
if [ "$2" == "" ]
then
        python3 /sbin/dplyd-orchst-cnfgrStore.py "$1"
        if [ "$?" != 0 ]
        then
                exit
        fi
else
        python3 /sbin/dplyd-orchst-cnfgrStore.py "$1" "$2"
        if [ "$?" != 0 ]
        then
                exit
        fi
fi
cp         -f "/dplyd/$1/profile" "/home/$1/.profile"
chmod      0600                   "/home/$1/.profile"
chown      -R $1:$1 "/home/$1"
restorecon -r       "/home/$1"
