#!/bin/sh
if [ "$1" == ""   ]
then
	 echo "Project ID not provided"
	 exit
fi
loginctl disable-linger "$1"
dplyd-orchst-prjct-strg-detach "$1"
rm       -rf "/etc/dplyd/$1"
userdel  -r  "$1"
rm       -rf "/home/$1"
rm       -rf "/etc/nginx/dplyd/http-$1.conf"
rm       -rf "/etc/nginx/dplyd/htts-$1.conf"
