#!/bin/sh
if [ "$1" == "" ]
then
	echo "Project ID not provided"
	exit
fi
if ! id -u $1 > /dev/null
then
	echo "Project does not exist"
	exit
fi
umount -l  "/home/$1"
if [ "$?" != 0 ]
then
        umount -f "/home/$1"
fi
loginctl disable-linger "$1"
sed    -i  "/\/home\/$1/d" '/etc/fstab'
systemctl daemon-reload
mount  -a
