#!/bin/sh
cp -rf ./dplyd* /sbin/
chmod 0700 /sbin/dplyd*
chmod 0755 /sbin/dplyd-orchst-prjct-launch
chmod 0755 /sbin/dplyd-orchst-prjct-launch.py
chmod 0755 /sbin/dplyd-orchst-prjct-manage
chmod 0755 /sbin/dplyd-orchst-prjct-shtdwn
